### ISSUE TITLE
base_model.py and learners code quality and doc

### ISSUE THREAD

**Issue by BielStela** [phi-grib/flame#91]
All the learners and base model should be cleaned a lot and well documented

**Comment by manuelpastor** [comment]
I agree

**Comment by josecarlosgomezt** [comment]
I have changed the code a lot. There are changes yet to be implemented such as more detailed documentation in functions and other details. Still, changes are enough to perform a pull request as some bugs were also fixed in the code.

Please check it and let me know if you have any other further suggestions to keep improving code quality and doc.

**Comment by manuelpastor** [comment]
The quality of the code is now much better, well done!
However, another review will be needed to document functions properly. I will remove the HIGH PRIORITY label
